---
- name: Patch Windows Server
  hosts: all
  gather_facts: no
  tasks:

    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
      register: update_result

    - name: Reboot the server if required
      win_reboot:
        reboot_timeout: 120
      when: update_result.reboot_required
