---
- name: Patch Windows Server 2019 and always reboot
  hosts: all
  gather_facts: no
  tasks:

    - name: Install Windows updates (Security, Critical, Rollups)
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        reboot: no  # We'll control the reboot ourselves
      register: patch_result
      
    - name: Force reboot after patching (always)
      win_reboot:
        reboot_timeout: 120
        pre_reboot_delay: 30
        post_reboot_delay: 60
