---
- name: Reboot Windows servers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Reboot the Windows machine
      win_reboot:
        reboot_timeout: 600
        test_command: hostname
      register: reboot_status
