- name: Import test.pfx and bind to IIS site 'MyWebsite'
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy test.pfx to remote host
      ansible.windows.win_copy:
        src: ./test.pfx
        dest: C:\Temp\test.pfx

    - name: Import test.pfx into LocalMachine\My store
      ansible.windows.win_shell: |
        $certPassword = ConvertTo-SecureString "Test1234" -AsPlainText -Force
        Import-PfxCertificate -FilePath "C:\Temp\test.pfx" -CertStoreLocation "Cert:\LocalMachine\My" -Password $certPassword

    - name: Get thumbprint of imported certificate
      ansible.windows.win_shell: |
        $cert = Get-PfxCertificate -FilePath "C:\Temp\test.pfx"
        Write-Output $cert.Thumbprint
      register: cert_thumbprint_raw

    - name: Set thumbprint fact
      set_fact:
        cert_thumbprint: "{{ cert_thumbprint_raw.stdout | trim }}"

    - name: Add HTTPS binding to IIS site 'MyWebsite'
      ansible.windows.win_shell: |
        Import-Module WebAdministration
        New-WebBinding -Name "MyWebsite" -Protocol https -Port 443 -IPAddress "*" -HostHeader ""
        Get-WebBinding -Name "MyWebsite" -Protocol "https" | ForEach-Object {
          $binding = $_
          $binding.AddSslCertificate("{{ cert_thumbprint }}", "My")
        }

    - name: Remove the copied certificate file
      ansible.windows.win_file:
        path: C:\Temp\test.pfx
        state: absent
