---
- name: Install a PFX SSL certificate and bind it to an IIS site
  hosts: all
  gather_facts: no

  tasks:
    - name: Create temp folder on remote host
      ansible.windows.win_file:
        path: "C:\\Temp"
        state: directory

    - name: Copy PFX certificate to remote host
      ansible.windows.win_copy:
        src: "files/mycert.pfx"
        dest: "C:\\Temp\\mycert.pfx"

    - name: Import certificate into WebHosting store
      community.windows.win_certificate_store:
        path: "C:\\Temp\\mycert.pfx"
        password: "MySecretPassword"
        store_name: "WebHosting"
        state: present
        friendly_name: "MyNewCert"
        valid_only: yes

    - name: Get thumbprint of installed certificate
      community.windows.win_certificate_info:
        store_name: "WebHosting"
        friendly_name: "MyNewCert"
      register: cert_info

    - name: Bind certificate to IIS site
      community.windows.win_iis_webbinding:
        name: "MyWebsite"
        protocol: https
        port: 443
        ip: "*"
        certificate_hash: "{{ cert_info.thumbprints[0] }}"
        certificate_store_name: "WebHosting"
        state: present

    - name: Delete temporary PFX file
      ansible.windows.win_file:
        path: "C:\\Temp\\mycert.pfx"
        state: absent
